// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: assignment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// list
type GetAssignmentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentListReq) Reset() {
	*x = GetAssignmentListReq{}
	mi := &file_assignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentListReq) ProtoMessage() {}

func (x *GetAssignmentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentListReq.ProtoReflect.Descriptor instead.
func (*GetAssignmentListReq) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssignmentListReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_assignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *Title) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Title) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetAssignmentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []*Title               `protobuf:"bytes,1,rep,name=Titles,proto3" json:"Titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentListResp) Reset() {
	*x = GetAssignmentListResp{}
	mi := &file_assignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentListResp) ProtoMessage() {}

func (x *GetAssignmentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentListResp.ProtoReflect.Descriptor instead.
func (*GetAssignmentListResp) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssignmentListResp) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

// info
type GetAssignmentInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentInfoReq) Reset() {
	*x = GetAssignmentInfoReq{}
	mi := &file_assignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentInfoReq) ProtoMessage() {}

func (x *GetAssignmentInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentInfoReq.ProtoReflect.Descriptor instead.
func (*GetAssignmentInfoReq) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssignmentInfoReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

type GetAssignmentInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleText     string                 `protobuf:"bytes,1,opt,name=TitleText,proto3" json:"TitleText,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Urls          []string               `protobuf:"bytes,3,rep,name=Urls,proto3" json:"Urls,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=Deadline,proto3" json:"Deadline,omitempty"`
	Year          int64                  `protobuf:"varint,5,opt,name=Year,proto3" json:"Year,omitempty"`
	Semester      string                 `protobuf:"bytes,6,opt,name=Semester,proto3" json:"Semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentInfoResp) Reset() {
	*x = GetAssignmentInfoResp{}
	mi := &file_assignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentInfoResp) ProtoMessage() {}

func (x *GetAssignmentInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentInfoResp.ProtoReflect.Descriptor instead.
func (*GetAssignmentInfoResp) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssignmentInfoResp) GetTitleText() string {
	if x != nil {
		return x.TitleText
	}
	return ""
}

func (x *GetAssignmentInfoResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetAssignmentInfoResp) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *GetAssignmentInfoResp) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GetAssignmentInfoResp) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetAssignmentInfoResp) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

// set
type SetAssignmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	TitleText     string                 `protobuf:"bytes,3,opt,name=TitleText,proto3" json:"TitleText,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	Urls          []string               `protobuf:"bytes,5,rep,name=Urls,proto3" json:"Urls,omitempty"`
	Deadline      string                 `protobuf:"bytes,6,opt,name=Deadline,proto3" json:"Deadline,omitempty"`
	Year          int64                  `protobuf:"varint,7,opt,name=Year,proto3" json:"Year,omitempty"`
	Semester      string                 `protobuf:"bytes,8,opt,name=Semester,proto3" json:"Semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAssignmentReq) Reset() {
	*x = SetAssignmentReq{}
	mi := &file_assignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssignmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssignmentReq) ProtoMessage() {}

func (x *SetAssignmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssignmentReq.ProtoReflect.Descriptor instead.
func (*SetAssignmentReq) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{5}
}

func (x *SetAssignmentReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

func (x *SetAssignmentReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SetAssignmentReq) GetTitleText() string {
	if x != nil {
		return x.TitleText
	}
	return ""
}

func (x *SetAssignmentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SetAssignmentReq) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *SetAssignmentReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *SetAssignmentReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SetAssignmentReq) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type SetAssignmentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAssignmentResp) Reset() {
	*x = SetAssignmentResp{}
	mi := &file_assignment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssignmentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssignmentResp) ProtoMessage() {}

func (x *SetAssignmentResp) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssignmentResp.ProtoReflect.Descriptor instead.
func (*SetAssignmentResp) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{6}
}

func (x *SetAssignmentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// delete
type DelAssignmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentID  string                 `protobuf:"bytes,1,opt,name=AssignmentID,proto3" json:"AssignmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelAssignmentReq) Reset() {
	*x = DelAssignmentReq{}
	mi := &file_assignment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelAssignmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAssignmentReq) ProtoMessage() {}

func (x *DelAssignmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAssignmentReq.ProtoReflect.Descriptor instead.
func (*DelAssignmentReq) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{7}
}

func (x *DelAssignmentReq) GetAssignmentID() string {
	if x != nil {
		return x.AssignmentID
	}
	return ""
}

type DelAssignmentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelAssignmentResp) Reset() {
	*x = DelAssignmentResp{}
	mi := &file_assignment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelAssignmentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAssignmentResp) ProtoMessage() {}

func (x *DelAssignmentResp) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAssignmentResp.ProtoReflect.Descriptor instead.
func (*DelAssignmentResp) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{8}
}

func (x *DelAssignmentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// list selected
type GetAssignmentListSelectedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Year          int64                  `protobuf:"varint,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Semester      string                 `protobuf:"bytes,3,opt,name=Semester,proto3" json:"Semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentListSelectedReq) Reset() {
	*x = GetAssignmentListSelectedReq{}
	mi := &file_assignment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentListSelectedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentListSelectedReq) ProtoMessage() {}

func (x *GetAssignmentListSelectedReq) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentListSelectedReq.ProtoReflect.Descriptor instead.
func (*GetAssignmentListSelectedReq) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssignmentListSelectedReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetAssignmentListSelectedReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetAssignmentListSelectedReq) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type GetAssignmentListSelectedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []*Title               `protobuf:"bytes,1,rep,name=Titles,proto3" json:"Titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentListSelectedResp) Reset() {
	*x = GetAssignmentListSelectedResp{}
	mi := &file_assignment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentListSelectedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentListSelectedResp) ProtoMessage() {}

func (x *GetAssignmentListSelectedResp) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentListSelectedResp.ProtoReflect.Descriptor instead.
func (*GetAssignmentListSelectedResp) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{10}
}

func (x *GetAssignmentListSelectedResp) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

var File_assignment_proto protoreflect.FileDescriptor

const file_assignment_proto_rawDesc = "" +
	"\n" +
	"\x10assignment.proto\x12\n" +
	"assignment\",\n" +
	"\x14GetAssignmentListReq\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"+\n" +
	"\x05Title\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Text\x18\x02 \x01(\tR\x04Text\"B\n" +
	"\x15GetAssignmentListResp\x12)\n" +
	"\x06Titles\x18\x01 \x03(\v2\x11.assignment.TitleR\x06Titles\":\n" +
	"\x14GetAssignmentInfoReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\"\xaf\x01\n" +
	"\x15GetAssignmentInfoResp\x12\x1c\n" +
	"\tTitleText\x18\x01 \x01(\tR\tTitleText\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12\x12\n" +
	"\x04Urls\x18\x03 \x03(\tR\x04Urls\x12\x1a\n" +
	"\bDeadline\x18\x04 \x01(\tR\bDeadline\x12\x12\n" +
	"\x04Year\x18\x05 \x01(\x03R\x04Year\x12\x1a\n" +
	"\bSemester\x18\x06 \x01(\tR\bSemester\"\xe4\x01\n" +
	"\x10SetAssignmentReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\x12\x14\n" +
	"\x05Group\x18\x02 \x01(\tR\x05Group\x12\x1c\n" +
	"\tTitleText\x18\x03 \x01(\tR\tTitleText\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x12\n" +
	"\x04Urls\x18\x05 \x03(\tR\x04Urls\x12\x1a\n" +
	"\bDeadline\x18\x06 \x01(\tR\bDeadline\x12\x12\n" +
	"\x04Year\x18\a \x01(\x03R\x04Year\x12\x1a\n" +
	"\bSemester\x18\b \x01(\tR\bSemester\"'\n" +
	"\x11SetAssignmentResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"6\n" +
	"\x10DelAssignmentReq\x12\"\n" +
	"\fAssignmentID\x18\x01 \x01(\tR\fAssignmentID\"'\n" +
	"\x11DelAssignmentResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"d\n" +
	"\x1cGetAssignmentListSelectedReq\x12\x14\n" +
	"\x05Group\x18\x01 \x01(\tR\x05Group\x12\x12\n" +
	"\x04Year\x18\x02 \x01(\x03R\x04Year\x12\x1a\n" +
	"\bSemester\x18\x03 \x01(\tR\bSemester\"J\n" +
	"\x1dGetAssignmentListSelectedResp\x12)\n" +
	"\x06Titles\x18\x01 \x03(\v2\x11.assignment.TitleR\x06Titles2\xd4\x03\n" +
	"\x10assignmentClient\x12X\n" +
	"\x11GetAssignmentList\x12 .assignment.GetAssignmentListReq\x1a!.assignment.GetAssignmentListResp\x12X\n" +
	"\x11GetAssignmentInfo\x12 .assignment.GetAssignmentInfoReq\x1a!.assignment.GetAssignmentInfoResp\x12L\n" +
	"\rSetAssignment\x12\x1c.assignment.SetAssignmentReq\x1a\x1d.assignment.SetAssignmentResp\x12L\n" +
	"\rDelAssignment\x12\x1c.assignment.DelAssignmentReq\x1a\x1d.assignment.DelAssignmentResp\x12p\n" +
	"\x19GetAssignmentListSelected\x12(.assignment.GetAssignmentListSelectedReq\x1a).assignment.GetAssignmentListSelectedRespB\x06Z\x04./pbb\x06proto3"

var (
	file_assignment_proto_rawDescOnce sync.Once
	file_assignment_proto_rawDescData []byte
)

func file_assignment_proto_rawDescGZIP() []byte {
	file_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_proto_rawDesc), len(file_assignment_proto_rawDesc)))
	})
	return file_assignment_proto_rawDescData
}

var file_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_assignment_proto_goTypes = []any{
	(*GetAssignmentListReq)(nil),          // 0: assignment.GetAssignmentListReq
	(*Title)(nil),                         // 1: assignment.Title
	(*GetAssignmentListResp)(nil),         // 2: assignment.GetAssignmentListResp
	(*GetAssignmentInfoReq)(nil),          // 3: assignment.GetAssignmentInfoReq
	(*GetAssignmentInfoResp)(nil),         // 4: assignment.GetAssignmentInfoResp
	(*SetAssignmentReq)(nil),              // 5: assignment.SetAssignmentReq
	(*SetAssignmentResp)(nil),             // 6: assignment.SetAssignmentResp
	(*DelAssignmentReq)(nil),              // 7: assignment.DelAssignmentReq
	(*DelAssignmentResp)(nil),             // 8: assignment.DelAssignmentResp
	(*GetAssignmentListSelectedReq)(nil),  // 9: assignment.GetAssignmentListSelectedReq
	(*GetAssignmentListSelectedResp)(nil), // 10: assignment.GetAssignmentListSelectedResp
}
var file_assignment_proto_depIdxs = []int32{
	1,  // 0: assignment.GetAssignmentListResp.Titles:type_name -> assignment.Title
	1,  // 1: assignment.GetAssignmentListSelectedResp.Titles:type_name -> assignment.Title
	0,  // 2: assignment.assignmentClient.GetAssignmentList:input_type -> assignment.GetAssignmentListReq
	3,  // 3: assignment.assignmentClient.GetAssignmentInfo:input_type -> assignment.GetAssignmentInfoReq
	5,  // 4: assignment.assignmentClient.SetAssignment:input_type -> assignment.SetAssignmentReq
	7,  // 5: assignment.assignmentClient.DelAssignment:input_type -> assignment.DelAssignmentReq
	9,  // 6: assignment.assignmentClient.GetAssignmentListSelected:input_type -> assignment.GetAssignmentListSelectedReq
	2,  // 7: assignment.assignmentClient.GetAssignmentList:output_type -> assignment.GetAssignmentListResp
	4,  // 8: assignment.assignmentClient.GetAssignmentInfo:output_type -> assignment.GetAssignmentInfoResp
	6,  // 9: assignment.assignmentClient.SetAssignment:output_type -> assignment.SetAssignmentResp
	8,  // 10: assignment.assignmentClient.DelAssignment:output_type -> assignment.DelAssignmentResp
	10, // 11: assignment.assignmentClient.GetAssignmentListSelected:output_type -> assignment.GetAssignmentListSelectedResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_assignment_proto_init() }
func file_assignment_proto_init() {
	if File_assignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_proto_rawDesc), len(file_assignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_proto_msgTypes,
	}.Build()
	File_assignment_proto = out.File
	file_assignment_proto_goTypes = nil
	file_assignment_proto_depIdxs = nil
}
