// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"MuXiFresh-Be-2.0/app/review/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 审阅界面
				Method:  http.MethodPost,
				Path:    "/review",
				Handler: GetReviewHandler(serverCtx),
			},
			{
				// 调整录取状态
				Method:  http.MethodPost,
				Path:    "/review/admission_status",
				Handler: SetAdmissionStatusHandler(serverCtx),
			},
			{
				// 一键导出 Excel（包含每个组的名单）
				Method:  http.MethodPost,
				Path:    "/review/export",
				Handler: ExportReviewExcelHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2"),
	)
}
