// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: assignment.proto

package assignmentclient

import (
	"context"

	"MuXiFresh-Be-2.0/app/task/cmd/rpc/assignment/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelAssignmentReq              = pb.DelAssignmentReq
	DelAssignmentResp             = pb.DelAssignmentResp
	GetAssignmentInfoReq          = pb.GetAssignmentInfoReq
	GetAssignmentInfoResp         = pb.GetAssignmentInfoResp
	GetAssignmentListReq          = pb.GetAssignmentListReq
	GetAssignmentListResp         = pb.GetAssignmentListResp
	GetAssignmentListSelectedReq  = pb.GetAssignmentListSelectedReq
	GetAssignmentListSelectedResp = pb.GetAssignmentListSelectedResp
	SetAssignmentReq              = pb.SetAssignmentReq
	SetAssignmentResp             = pb.SetAssignmentResp
	Title                         = pb.Title

	AssignmentClient interface {
		GetAssignmentList(ctx context.Context, in *GetAssignmentListReq, opts ...grpc.CallOption) (*GetAssignmentListResp, error)
		GetAssignmentInfo(ctx context.Context, in *GetAssignmentInfoReq, opts ...grpc.CallOption) (*GetAssignmentInfoResp, error)
		SetAssignment(ctx context.Context, in *SetAssignmentReq, opts ...grpc.CallOption) (*SetAssignmentResp, error)
		DelAssignment(ctx context.Context, in *DelAssignmentReq, opts ...grpc.CallOption) (*DelAssignmentResp, error)
		GetAssignmentListSelected(ctx context.Context, in *GetAssignmentListSelectedReq, opts ...grpc.CallOption) (*GetAssignmentListSelectedResp, error)
	}

	defaultAssignmentClient struct {
		cli zrpc.Client
	}
)

func NewAssignmentClient(cli zrpc.Client) AssignmentClient {
	return &defaultAssignmentClient{
		cli: cli,
	}
}

func (m *defaultAssignmentClient) GetAssignmentList(ctx context.Context, in *GetAssignmentListReq, opts ...grpc.CallOption) (*GetAssignmentListResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.GetAssignmentList(ctx, in, opts...)
}

func (m *defaultAssignmentClient) GetAssignmentInfo(ctx context.Context, in *GetAssignmentInfoReq, opts ...grpc.CallOption) (*GetAssignmentInfoResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.GetAssignmentInfo(ctx, in, opts...)
}

func (m *defaultAssignmentClient) SetAssignment(ctx context.Context, in *SetAssignmentReq, opts ...grpc.CallOption) (*SetAssignmentResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.SetAssignment(ctx, in, opts...)
}

func (m *defaultAssignmentClient) DelAssignment(ctx context.Context, in *DelAssignmentReq, opts ...grpc.CallOption) (*DelAssignmentResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.DelAssignment(ctx, in, opts...)
}

func (m *defaultAssignmentClient) GetAssignmentListSelected(ctx context.Context, in *GetAssignmentListSelectedReq, opts ...grpc.CallOption) (*GetAssignmentListSelectedResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.GetAssignmentListSelected(ctx, in, opts...)
}
