// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: comment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// get
type GetSubmissionCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionID  string                 `protobuf:"bytes,1,opt,name=SubmissionID,proto3" json:"SubmissionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionCommentReq) Reset() {
	*x = GetSubmissionCommentReq{}
	mi := &file_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionCommentReq) ProtoMessage() {}

func (x *GetSubmissionCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionCommentReq.ProtoReflect.Descriptor instead.
func (*GetSubmissionCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubmissionCommentReq) GetSubmissionID() string {
	if x != nil {
		return x.SubmissionID
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentID     string                 `protobuf:"bytes,1,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=Group,proto3" json:"Group,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	FatherID      string                 `protobuf:"bytes,7,opt,name=FatherID,proto3" json:"FatherID,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetCommentID() string {
	if x != nil {
		return x.CommentID
	}
	return ""
}

func (x *Comment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Comment) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Comment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Comment) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetFatherID() string {
	if x != nil {
		return x.FatherID
	}
	return ""
}

func (x *Comment) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetSubmissionCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=Comments,proto3" json:"Comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionCommentResp) Reset() {
	*x = GetSubmissionCommentResp{}
	mi := &file_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionCommentResp) ProtoMessage() {}

func (x *GetSubmissionCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionCommentResp.ProtoReflect.Descriptor instead.
func (*GetSubmissionCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubmissionCommentResp) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// set
type SetSubmissionCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SubmissionID  string                 `protobuf:"bytes,2,opt,name=SubmissionID,proto3" json:"SubmissionID,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubmissionCommentReq) Reset() {
	*x = SetSubmissionCommentReq{}
	mi := &file_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubmissionCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubmissionCommentReq) ProtoMessage() {}

func (x *SetSubmissionCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubmissionCommentReq.ProtoReflect.Descriptor instead.
func (*SetSubmissionCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{3}
}

func (x *SetSubmissionCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetSubmissionCommentReq) GetSubmissionID() string {
	if x != nil {
		return x.SubmissionID
	}
	return ""
}

func (x *SetSubmissionCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SetSubmissionCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubmissionCommentResp) Reset() {
	*x = SetSubmissionCommentResp{}
	mi := &file_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubmissionCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubmissionCommentResp) ProtoMessage() {}

func (x *SetSubmissionCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubmissionCommentResp.ProtoReflect.Descriptor instead.
func (*SetSubmissionCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{4}
}

func (x *SetSubmissionCommentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// del
type DelSubmissionCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentID     string                 `protobuf:"bytes,1,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSubmissionCommentReq) Reset() {
	*x = DelSubmissionCommentReq{}
	mi := &file_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSubmissionCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSubmissionCommentReq) ProtoMessage() {}

func (x *DelSubmissionCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSubmissionCommentReq.ProtoReflect.Descriptor instead.
func (*DelSubmissionCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DelSubmissionCommentReq) GetCommentID() string {
	if x != nil {
		return x.CommentID
	}
	return ""
}

type DelSubmissionCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSubmissionCommentResp) Reset() {
	*x = DelSubmissionCommentResp{}
	mi := &file_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSubmissionCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSubmissionCommentResp) ProtoMessage() {}

func (x *DelSubmissionCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSubmissionCommentResp.ProtoReflect.Descriptor instead.
func (*DelSubmissionCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{6}
}

func (x *DelSubmissionCommentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// is
type IsMyCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CommentID     string                 `protobuf:"bytes,2,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMyCommentReq) Reset() {
	*x = IsMyCommentReq{}
	mi := &file_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMyCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMyCommentReq) ProtoMessage() {}

func (x *IsMyCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMyCommentReq.ProtoReflect.Descriptor instead.
func (*IsMyCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{7}
}

func (x *IsMyCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsMyCommentReq) GetCommentID() string {
	if x != nil {
		return x.CommentID
	}
	return ""
}

type IsMyCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMyCommentResp) Reset() {
	*x = IsMyCommentResp{}
	mi := &file_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMyCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMyCommentResp) ProtoMessage() {}

func (x *IsMyCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMyCommentResp.ProtoReflect.Descriptor instead.
func (*IsMyCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{8}
}

func (x *IsMyCommentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// reply
type ReplySubmissionCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SubmissionID  string                 `protobuf:"bytes,2,opt,name=submissionID,proto3" json:"submissionID,omitempty"`
	FatherID      string                 `protobuf:"bytes,3,opt,name=fatherID,proto3" json:"fatherID,omitempty"` // 父评论 ID，必填
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplySubmissionCommentReq) Reset() {
	*x = ReplySubmissionCommentReq{}
	mi := &file_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplySubmissionCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplySubmissionCommentReq) ProtoMessage() {}

func (x *ReplySubmissionCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplySubmissionCommentReq.ProtoReflect.Descriptor instead.
func (*ReplySubmissionCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ReplySubmissionCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplySubmissionCommentReq) GetSubmissionID() string {
	if x != nil {
		return x.SubmissionID
	}
	return ""
}

func (x *ReplySubmissionCommentReq) GetFatherID() string {
	if x != nil {
		return x.FatherID
	}
	return ""
}

func (x *ReplySubmissionCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplySubmissionCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplySubmissionCommentResp) Reset() {
	*x = ReplySubmissionCommentResp{}
	mi := &file_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplySubmissionCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplySubmissionCommentResp) ProtoMessage() {}

func (x *ReplySubmissionCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplySubmissionCommentResp.ProtoReflect.Descriptor instead.
func (*ReplySubmissionCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{10}
}

func (x *ReplySubmissionCommentResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_comment_proto protoreflect.FileDescriptor

const file_comment_proto_rawDesc = "" +
	"\n" +
	"\rcomment.proto\x12\acomment\"=\n" +
	"\x17GetSubmissionCommentReq\x12\"\n" +
	"\fSubmissionID\x18\x01 \x01(\tR\fSubmissionID\"\xdb\x01\n" +
	"\aComment\x12\x1c\n" +
	"\tCommentID\x18\x01 \x01(\tR\tCommentID\x12\x16\n" +
	"\x06Avatar\x18\x02 \x01(\tR\x06Avatar\x12\x1a\n" +
	"\bNickName\x18\x03 \x01(\tR\bNickName\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Group\x18\x05 \x01(\tR\x05Group\x12\x18\n" +
	"\aContent\x18\x06 \x01(\tR\aContent\x12\x1a\n" +
	"\bFatherID\x18\a \x01(\tR\bFatherID\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\b \x01(\tR\n" +
	"CreateTime\"H\n" +
	"\x18GetSubmissionCommentResp\x12,\n" +
	"\bComments\x18\x01 \x03(\v2\x10.comment.CommentR\bComments\"o\n" +
	"\x17SetSubmissionCommentReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\"\n" +
	"\fSubmissionID\x18\x02 \x01(\tR\fSubmissionID\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\".\n" +
	"\x18SetSubmissionCommentResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"7\n" +
	"\x17DelSubmissionCommentReq\x12\x1c\n" +
	"\tCommentID\x18\x01 \x01(\tR\tCommentID\".\n" +
	"\x18DelSubmissionCommentResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"F\n" +
	"\x0eIsMyCommentReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1c\n" +
	"\tCommentID\x18\x02 \x01(\tR\tCommentID\"%\n" +
	"\x0fIsMyCommentResp\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\"\x8d\x01\n" +
	"\x19ReplySubmissionCommentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\fsubmissionID\x18\x02 \x01(\tR\fsubmissionID\x12\x1a\n" +
	"\bfatherID\x18\x03 \x01(\tR\bfatherID\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"0\n" +
	"\x1aReplySubmissionCommentResp\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\bR\x04flag2\xcb\x03\n" +
	"\rcommentClient\x12[\n" +
	"\x14GetSubmissionComment\x12 .comment.GetSubmissionCommentReq\x1a!.comment.GetSubmissionCommentResp\x12[\n" +
	"\x14SetSubmissionComment\x12 .comment.SetSubmissionCommentReq\x1a!.comment.SetSubmissionCommentResp\x12[\n" +
	"\x14DelSubmissionComment\x12 .comment.DelSubmissionCommentReq\x1a!.comment.DelSubmissionCommentResp\x12@\n" +
	"\vIsMyComment\x12\x17.comment.IsMyCommentReq\x1a\x18.comment.IsMyCommentResp\x12a\n" +
	"\x16ReplySubmissionComment\x12\".comment.ReplySubmissionCommentReq\x1a#.comment.ReplySubmissionCommentRespB\x06Z\x04./pbb\x06proto3"

var (
	file_comment_proto_rawDescOnce sync.Once
	file_comment_proto_rawDescData []byte
)

func file_comment_proto_rawDescGZIP() []byte {
	file_comment_proto_rawDescOnce.Do(func() {
		file_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)))
	})
	return file_comment_proto_rawDescData
}

var file_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_comment_proto_goTypes = []any{
	(*GetSubmissionCommentReq)(nil),    // 0: comment.GetSubmissionCommentReq
	(*Comment)(nil),                    // 1: comment.Comment
	(*GetSubmissionCommentResp)(nil),   // 2: comment.GetSubmissionCommentResp
	(*SetSubmissionCommentReq)(nil),    // 3: comment.SetSubmissionCommentReq
	(*SetSubmissionCommentResp)(nil),   // 4: comment.SetSubmissionCommentResp
	(*DelSubmissionCommentReq)(nil),    // 5: comment.DelSubmissionCommentReq
	(*DelSubmissionCommentResp)(nil),   // 6: comment.DelSubmissionCommentResp
	(*IsMyCommentReq)(nil),             // 7: comment.IsMyCommentReq
	(*IsMyCommentResp)(nil),            // 8: comment.IsMyCommentResp
	(*ReplySubmissionCommentReq)(nil),  // 9: comment.ReplySubmissionCommentReq
	(*ReplySubmissionCommentResp)(nil), // 10: comment.ReplySubmissionCommentResp
}
var file_comment_proto_depIdxs = []int32{
	1,  // 0: comment.GetSubmissionCommentResp.Comments:type_name -> comment.Comment
	0,  // 1: comment.commentClient.GetSubmissionComment:input_type -> comment.GetSubmissionCommentReq
	3,  // 2: comment.commentClient.SetSubmissionComment:input_type -> comment.SetSubmissionCommentReq
	5,  // 3: comment.commentClient.DelSubmissionComment:input_type -> comment.DelSubmissionCommentReq
	7,  // 4: comment.commentClient.IsMyComment:input_type -> comment.IsMyCommentReq
	9,  // 5: comment.commentClient.ReplySubmissionComment:input_type -> comment.ReplySubmissionCommentReq
	2,  // 6: comment.commentClient.GetSubmissionComment:output_type -> comment.GetSubmissionCommentResp
	4,  // 7: comment.commentClient.SetSubmissionComment:output_type -> comment.SetSubmissionCommentResp
	6,  // 8: comment.commentClient.DelSubmissionComment:output_type -> comment.DelSubmissionCommentResp
	8,  // 9: comment.commentClient.IsMyComment:output_type -> comment.IsMyCommentResp
	10, // 10: comment.commentClient.ReplySubmissionComment:output_type -> comment.ReplySubmissionCommentResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_comment_proto_init() }
func file_comment_proto_init() {
	if File_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_proto_goTypes,
		DependencyIndexes: file_comment_proto_depIdxs,
		MessageInfos:      file_comment_proto_msgTypes,
	}.Build()
	File_comment_proto = out.File
	file_comment_proto_goTypes = nil
	file_comment_proto_depIdxs = nil
}
