// Code generated by goctl. DO NOT EDIT.
package types

type ClickReq struct {
	Authorization string `header:"Authorization"`
}

type ClickResp struct {
	UserType   string `json:"user_type"`
	FormStatus string `json:"form_status"`
}

type CreateReq struct {
	Authorization string `header:"Authorization"`
	FormId        string `json:"form_id,optional"`
	Avatar        string `json:"avatar"`
	Major         string `json:"major"`
	Grade         string `json:"grade"`
	Gender        string `json:"gender"`
	Phone         string `json:"phone"`
	Group         string `json:"group,options=[Product,Design,Frontend,Backend,Android,Operation]"`
	Reason        string `json:"reason"`
	Knowledge     string `json:"knowledge"`
	SelfIntro     string `json:"self_intro"`
	ExtraQuestion string `json:"extra_question"`
}

type CreateResp struct {
	Flag bool `json:"flag"`
}

type CheckReq struct {
	Authorization string `header:"Authorization"`
	EntryFormID   string `form:"entry_form_id"`
}

type CheckResp struct {
	FormId        string `json:"form_id"`
	Avatar        string `json:"avatar"`
	Major         string `json:"major"`
	Grade         string `json:"grade"`
	Gender        string `json:"gender"`
	Phone         string `json:"phone"`
	Group         string `json:"group"`
	Reason        string `json:"reason"`
	Knowledge     string `json:"knowledge"`
	SelfIntro     string `json:"self_intro"`
	ExtraQuestion string `json:"extra_question"`
}

// 查询报名截止时间；cycle 省略时取当前届次
type GetRecruitDeadlineReq struct {
	Cycle string `form:"cycle,optional"`
}

type GetRecruitDeadlineResp struct {
	Cycle    string `json:"cycle"`
	Deadline string `json:"deadline"`
	Rev      int64  `json:"rev"`
}

// 设置报名截止时间（rev 为乐观锁版本号，首次写入传 0）
type SetRecruitDeadlineReq struct {
	Authorization string `header:"Authorization"`
	Cycle         string `json:"cycle"`
	Deadline      string `json:"deadline"`
	Rev           int64  `json:"rev,optional,default=0"`
}

type SetRecruitDeadlineResp struct {
	Cycle    string `json:"cycle"`
	Deadline string `json:"deadline"`
	Rev      int64  `json:"rev"`
}
