// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ExportReviewExcelReq struct {
	Authorization string `header:"Authorization"`
	Year          int    `json:"year"`
	Season        string `json:"season,options=[autumn,spring]"`
	Group         string `json:"group,optional,options=[All,Product,Design,Frontend,Backend,Android,Operation]"` // 为空或 All 时导出所有组
	Grade         string `json:"grade,optional"`
	School        string `json:"school,optional"`
	Status        string `json:"status,optional"`
}

type GetReviewReq struct {
	Authorization string `header:"Authorization"`
	Year          int    `json:"year"`
	Group         string `json:"group,options=[All,Product,Design,Frontend,Backend,Android,Operation]"`
	Season        string `json:"season,options=[autumn,spring]"`
	Grade         string `json:"grade,optional"`
	School        string `json:"school,optional"`
	Status        string `json:"status,optional"`
	Name          string `json:"name,optional"`
	Page          int64  `json:"page,optional,default=1"`
	PageSize      int64  `json:"page_size,optional"`
}

type GetReviewResp struct {
	Rows  []Row `json:"rows"`
	Total int64 `json:"total"`
}

type Row struct {
	Name             string `json:"name"`
	Grade            string `json:"grader"`
	School           string `json:"school"`
	Group            string `json:"group"`
	Gender           string `json:"gender"`
	Major            string `json:"major"`
	Phone            string `json:"phone"`
	QQ               string `json:"qq"`
	FormID           string `json:"form_id"`
	UserId           string `json:"user_id"`
	AdmissionStatus  string `json:"admission_status"`
	ScheduleID       string `json:"schedule_id"`
	Understanding    string `json:"understanding"`
	Reason           string `json:"reason"`
	SelfIntro        string `json:"selfintro"`
	ExtraQuestion    string `json:"extra_question"`
	InterviewComment string `json:"interview_comment"`
}

type SetAdmissionStatusReq struct {
	Authorization string `header:"Authorization"`
	ScheduleID    string `json:"schedule_id"`
	NewStatus     string `json:"new_status,options=[已报名,实习期,已转正]"`
}

type SetAdmissionStatusResp struct {
	Flag bool `json:"flag"`
}

type SetInterviewCommentReq struct {
	Authorization string `header:"Authorization"`
	FormID        string `json:"form_id"`
	Comment       string `json:"comment"`
}

type SetInterviewCommentResp struct {
	Flag bool `json:"flag"`
}
