// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ExportReviewExcelReq struct {
	Authorization string `header:"Authorization"`
	Year          int    `json:"year"`
	Season        string `json:"season,options=[autumn,spring]"`
	Group         string `json:"group,optional"` // 如果为空，导出所有组
	Grade         string `json:"grade,optional"`
	School        string `json:"school,optional"`
	Status        string `json:"status,optional"`
}

type GetReviewReq struct {
	Authorization string `header:"Authorization"`
	Year          int    `json:"year"`
	Group         string `json:"group"`
	Season        string `json:"season,options=[autumn,spring]"`
	Grade         string `json:"grade,optional"`
	School        string `json:"school,optional"`
	Status        string `json:"status,optional"`
}

type GetReviewResp struct {
	Rows []Row `json:"rows"`
}

type Row struct {
	Name            string `json:"name"`
	Grade           string `json:"grader"`
	School          string `json:"school"`
	Group           string `json:"group"`
	Gender          string `json:"gender"`
	FormID          string `json:"form_id"`
	ExamStuatus     string `json:"exam_status"`
	UserId          string `json:"user_id"`
	AdmissionStatus string `json:"admission_status"`
	ScheduleID      string `json:"schedule_id"`
	Understanding   string `json:"understanding"`
	Reason          string `json:"reason"`
	SelfIntro       string `json:"selfintro"`
}

type SetAdmissionStatusReq struct {
	Authorization string `header:"Authorization"`
	ScheduleID    string `json:"schedule_id"`
	NewStatus     string `json:"new_status,options=[已报名,实习期,已转正]"`
}

type SetAdmissionStatusResp struct {
	Flag bool `json:"flag"`
}
